package com.hrm.attendance.model;

import java.util.Date;
import java.util.UUID;

public class AttendanceRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_records.record_id
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    private UUID recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_records.auth_user_id
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    private Object authUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_records.check_in_time
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    private Date checkInTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_records.check_out_time
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    private Date checkOutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_records.record_date
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    private Date recordDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_records.record_id
     *
     * @return the value of attendance_records.record_id
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public UUID getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_records.record_id
     *
     * @param recordId the value for attendance_records.record_id
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public void setRecordId(UUID recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_records.auth_user_id
     *
     * @return the value of attendance_records.auth_user_id
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public Object getAuthUserId() {
        return authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_records.auth_user_id
     *
     * @param authUserId the value for attendance_records.auth_user_id
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public void setAuthUserId(Object authUserId) {
        this.authUserId = authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_records.check_in_time
     *
     * @return the value of attendance_records.check_in_time
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public Date getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_records.check_in_time
     *
     * @param checkInTime the value for attendance_records.check_in_time
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public void setCheckInTime(Date checkInTime) {
        this.checkInTime = checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_records.check_out_time
     *
     * @return the value of attendance_records.check_out_time
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public Date getCheckOutTime() {
        return checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_records.check_out_time
     *
     * @param checkOutTime the value for attendance_records.check_out_time
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public void setCheckOutTime(Date checkOutTime) {
        this.checkOutTime = checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_records.record_date
     *
     * @return the value of attendance_records.record_date
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_records.record_date
     *
     * @param recordDate the value for attendance_records.record_date
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
}