package com.hrm.attendance.mapper;

import com.hrm.attendance.model.AttendanceRecord;
import java.util.List;
import java.util.UUID;

public interface AttendanceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_records
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    int deleteByPrimaryKey(UUID recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_records
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    int insert(AttendanceRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_records
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    AttendanceRecord selectByPrimaryKey(UUID recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_records
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    List<AttendanceRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_records
     *
     * @mbg.generated Wed Dec 03 11:13:51 ICT 2025
     */
    int updateByPrimaryKey(AttendanceRecord row);
}