package com.hrm.auth.model;

import java.util.UUID;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    private UUID roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_name
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_id
     *
     * @return the value of roles.role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public UUID getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_id
     *
     * @param roleId the value for roles.role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public void setRoleId(UUID roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_name
     *
     * @return the value of roles.role_name
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_name
     *
     * @param roleName the value for roles.role_name
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}