package com.hrm.auth.model;

import java.util.UUID;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    private UUID userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_role_id
     *
     * @return the value of user_roles.user_role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public UUID getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_role_id
     *
     * @param userRoleId the value for user_roles.user_role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public void setUserRoleId(UUID userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_id
     *
     * @return the value of user_roles.user_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_id
     *
     * @param userId the value for user_roles.user_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.role_id
     *
     * @return the value of user_roles.role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.role_id
     *
     * @param roleId the value for user_roles.role_id
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}