package com.hrm.employee.mapper;

import com.hrm.employee.model.Employee;
import java.util.List;
import java.util.UUID;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    int deleteByPrimaryKey(UUID employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    int insert(Employee row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    Employee selectByPrimaryKey(UUID employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    int updateByPrimaryKey(Employee row);
}