package com.hrm.auth.mapper;

import com.hrm.auth.model.Role;
import java.util.List;
import java.util.UUID;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    int deleteByPrimaryKey(UUID roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    int insert(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    Role selectByPrimaryKey(UUID roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    int updateByPrimaryKey(Role row);
}