package com.hrm.auth.mapper;

import com.hrm.auth.model.UserRole;
import java.util.List;
import java.util.UUID;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    int deleteByPrimaryKey(UUID userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    int insert(UserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    UserRole selectByPrimaryKey(UUID userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    List<UserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Tue Dec 02 10:18:24 ICT 2025
     */
    int updateByPrimaryKey(UserRole row);
}