package com.hrm.employee.model;

import java.util.Date;
import java.util.UUID;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.employee_id
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private UUID employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.auth_user_id
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private Object authUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.first_name
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.last_name
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.position
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.department
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.hire_date
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private Date hireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.phone_number
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.employee_id
     *
     * @return the value of employees.employee_id
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public UUID getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.employee_id
     *
     * @param employeeId the value for employees.employee_id
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setEmployeeId(UUID employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.auth_user_id
     *
     * @return the value of employees.auth_user_id
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public Object getAuthUserId() {
        return authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.auth_user_id
     *
     * @param authUserId the value for employees.auth_user_id
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setAuthUserId(Object authUserId) {
        this.authUserId = authUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.first_name
     *
     * @return the value of employees.first_name
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.first_name
     *
     * @param firstName the value for employees.first_name
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.last_name
     *
     * @return the value of employees.last_name
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.last_name
     *
     * @param lastName the value for employees.last_name
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.position
     *
     * @return the value of employees.position
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.position
     *
     * @param position the value for employees.position
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.department
     *
     * @return the value of employees.department
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.department
     *
     * @param department the value for employees.department
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.hire_date
     *
     * @return the value of employees.hire_date
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.hire_date
     *
     * @param hireDate the value for employees.hire_date
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.phone_number
     *
     * @return the value of employees.phone_number
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.phone_number
     *
     * @param phoneNumber the value for employees.phone_number
     *
     * @mbg.generated Wed Dec 03 09:58:51 ICT 2025
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }
}